name: "Aridaman's Happy Place"

options:
  deploymentTarget:
    iOS: "26.0"
  createIntermediateGroups: true
  developmentLanguage: en

settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: com.aridaman.happyplace
    PRODUCT_NAME: "Aridman's Happy Place"
    SWIFT_VERSION: "5.0"
    TARGETED_DEVICE_FAMILY: "1,2"
    SUPPORTS_MACCATALYST: NO
    CODE_SIGNING_ALLOWED: NO
    CODE_SIGNING_REQUIRED: NO
    CODE_SIGN_IDENTITY: ""
    DEVELOPMENT_TEAM: ""

targets:
  AridmansHappyPlace:
    type: application
    platform: iOS

    sources:
      - path: AridmansHappyPlace
        excludes:
          - "*.plist"

    info:
      path: AridamansHappyPlace/Info.plist

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.aridaman.happyplace
        PRODUCT_NAME: "Aridaman's Happy Place"
        SWIFT_VERSION: "5.0"
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_MACCATALYST: NO
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO
        CODE_SIGN_IDENTITY: ""
        DEVELOPMENT_TEAM: ""
